vich_uploader:
    db_driver: orm

    mappings:

       room_images:
           uri_prefix: '%upload_dir%'
           upload_destination: '%kernel.project_dir%/public%upload_dir%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true

       other_room_images:
           uri_prefix: '%upload_dir%'
           upload_destination: '%kernel.project_dir%/public%upload_dir%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true

       equipment_images:
            uri_prefix: '%upload_dir%'
            upload_destination: '%kernel.project_dir%/public%upload_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

       services_images:
            uri_prefix: '%upload_dir%'
            upload_destination: '%kernel.project_dir%/public%upload_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

       employees:
            uri_prefix: '%upload_dir%'
            upload_destination: '%kernel.project_dir%/public%upload_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true